licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "embed",
    srcs = ["embed_main.cc"],
    deps = ["//external:base"],
)

cc_binary(
    name = "free_port",
    srcs = ["free_port_main.cc"],
    deps = ["//external:base"],
)
